### ISSUE TITLE
code highlighting

### ISSUE THREAD

**Issue by dagolinuxoid** [thejerf/markdir#1]
Is it easy to implement a code highlighting (using aka github markdown extended version) via markdir:
```javascript
function go() {
  const markdir='is pretty cool';
  return markdir;
}

**Comment by thejerf** [comment]
To a first approximation, it looks like you could swap out the

    output := blackfriday.MarkdownCommon(input)

line with

    output := github_flavored_markdown.Markdown(input)

And you'd need to integrate the [CompleteHTMLPage](https://godoc.org/github.com/shurcooL/github_flavored_markdown#example-Markdown--CompleteHTMLPage) example on the github_flavored_markdown repo, which should drop right in since this does absolutely nothing fancy.

Because one of the purposes of markdir is to be a very simple example, I don't really want to integrate that here. But if you'd like to fork (and preferably give it a bit of a rename; I'm not trying to claim "markdir" in general so "markdir-github" would be fine, or whatever else you like with a new basename), and make these changes, I'd be happy to link to your fork in the README.md.
